workflows:
  android-workflow:
    name: Lost-and-Found Build
    max_build_duration: 60
    environment:
      vars:
        BUILD_MODE: debug
      android:
        gradle: latest        
        java: openjdk11       
    scripts:
      - name: Build APK
        script: gradle assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
