workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUILD_MODE: release
    scripts:
      - name: Install Gradle dependencies
        script: ./gradlew dependencies
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/**/*.apk
